config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

  root 'home#index'
  resources :todoo

end

app/models/todoo.rb
class Todoo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todoo

  after_create :init

  def init
    BOOKS.each do |item|
      @todo = Todoo.create(name: item, done: false, user: self)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
end

app/controllers/books.rb
BOOKS = ["A book with more than 500 pages",
    "A classic romance",
    "A book that became a movie",
    "A book published this year",
    "A book with a number in the title",
    "A book written by someone under 30",
    "A book with nonhuman characters",
    "A funny book",
    "A book by a female author",
    "A mystery or thriller",
    "A book with a one-word title",
    "A book of short stories",
    "A book set in a different country",
    "A nonfiction book",
    "A popular author's ﬁrst book",
    "A book from an author you love that you haven't read yet",
    "A book a friend recommended",
    "A Pulitzer Prize-winning book",
    "A book based on a true story",
    "A book at the bottom of your to-read list",
    "A book your mom loves",
    "A book that scares you",
    "A book more than 100 years old",
    "A book based entirely on its cover",
    "A book you were supposed to read in school but didn't",
    "A memoir",
    "A book you can ﬁnish in a day",
    "A book with antonyms in the title",
    "A book set somewhere you've always wanted to visit",
    "A book that came out the year you were born",
    "A book with bad reviews",
    "A trilogy",
    "A book from your childhood",
    "A book with a love triangle",
    "A book set in the future",
    "A book set in high school",
    "A book with a color in the title",
    "A book that made you cry",
    "A book with magic",
    "A graphic novel",
    "A book by an author you've never read before",
    "A book you own but have never read",
    "A book that takes place in your hometown",
    "A book that was originally written in a different language",
    "A book set during Christmas",
    "A book written by an author with your same initials",
    "A play",
    "A banned book",
    "A book based on or turned into a TV show",
    "A book you started but never finished"]

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if user_signed_in?
            redirect_to :controller => 'todoo', :action => 'index'
        end
    end
end

app/controllers/todoo_controller.rb
class TodooController < ApplicationController

    before_filter :set_current_user

    def set_current_user
        @current ||= current_user
    end

    def index
        @todos = Todoo.where(user_id: current_user.id, done: false)
        @todone = Todoo.where(user_id: current_user.id, done: true)
    end

    def new
        @todo = Todoo.new
    end

    # For now, this will go unused, because we have a set number of books for people to read.
    def create
        @todo = Todoo.new(todo_params)
        @todo.user = current_user
        if @todo.save
            redirect_to todoo_index_path, :notice => "Your book was created!"
        else
            render "new"
        end
    end

    def update
        @todo = Todoo.find(params[:id])
        if @todo.update_attribute(:done, true)
            redirect_to todoo_index_path # When a book is marked as finished
        else
            redirect_to todoo_index_path # If for some reason a book isn't able to be marked
        end
    end

    def destroy
        @todo = Todoo.find(params[:id])
        if @todo.update_attribute(:done, false)
            redirect_to todoo_index_path # When someone unmarks a book
        else
            redirect_to todoo_index_path
        end
        # Were this a standard todo list, we would have the below for destroyed items:
        # @todo.destroy
        # redirect_to todoo_index_path, :notice => "Your todo item is deleted"
    end

    def todo_params
        params.require(:todoo).permit(:name, :done)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todoo_helper.rb
module TodooHelper
end

app/views/home/index.html.erb
<div class="bg"></div>
<div class="jumbotron text-center">
    <h1>Reading Challenge 2015</h1>
    <p class="lead">Read 50 books this year, and track your progress</p>
</div>

<div class="container">
    <div class="row text-center">
        <h2>This year, make it your goal to <strong>read.</strong></h2>
    </div>
    <div class="row">
        <div class="col-md-6">
            It's no secret that reading is an important addition to any and every person's day.
            This year, make it a part of yours.
            Once you join, you'll find a set of book types to read. <br><br>
            A book you started but never finished.<br>
            <div class="text-right"> A book that came out the year you were born.</div>
            A book written by an author with your same initials.<br>
            <div class="text-right"> A book written by someone under 30. </div><br>
            Learn more about <strong>yourself</strong> and the <strong>world</strong> around you as you immerse yourself in 50 new stories all year.<br><br>
            <div class="text-center"> Follow <a href="https://twitter.com/hashtag/ReadingChallenge2015">#ReadingChallenge2015</a> for inspiration, and have fun!</div>
        </div>
        <div class="col-md-6">
            <a class="twitter-timeline" href="https://twitter.com/hashtag/ReadingChallenge2015" data-widget-id="557413244126896128">#ReadingChallenge2015 Tweets</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
    </div>
    <div class="row">
        <hr>
        <div class="col-md-6">
            <blockquote>
                <p>He that loves reading has everything within his reach.</p>
                <footer>William Godwin</footer>
                </blockquote>
        </div>
        <div class="col-md-6 text-right">
            <br>
            <address>
                <strong>Built by Cassidy Williams</strong><br>
                <a href="http://cassidoo.co">About</a> -
                <a href="http://github.com/cassidoo">GitHub</a> -
                <a href="http://twitter.com/superandomness">Twitter</a>
            </address>
        </div>
    </div>
</div>

<script>

var jumbo = $('.jumbotron').outerHeight();

function parallax(){
    var scrolled = $(window).scrollTop();
    $('.bg').css('height', (jumbo - scrolled) + 'px');
}

$(window).scroll(function(e){
    parallax();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Reading Challenge 2015</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
    <nav class="navbar navbar-default">
        <% if user_signed_in? %>
        <p class="navbar-text">
            Howdy! You're signed in as <%= current_user.email %>. Not you?
            <%= link_to "Sign out.", destroy_user_session_path, :method => :delete%>
        </p>
        <%else%>
        <div class="login navbar-text">
            <%= link_to "Sign up!", new_user_registration_path%> or <%=link_to "Sign in", new_user_session_path%>
        </div>

        <%end%>
    </nav>

    <% flash.each do |name,message|%>
    <%= content_tag :div, message, :id => "flash_#{name}" %>
    <%end%>

    <%= yield %>

</body>
</html>

app/views/todoo/index.html.erb
<div class="reading">
	<div class="page-header text-center">
		<h1>Reading Challenge 2015</h1>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<h2>Books to read</h2>

				<% if @todos.empty? %>

				<a href="https://twitter.com/intent/tweet?button_hashtag=ReadingChallenge2015&text=I%20finished%20the%202015%20Reading%20Challenge!" class="twitter-hashtag-button" data-related="superandomness" data-url="http://readingchallenge2015.herokuapp.com">Tweet #ReadingChallenge2015</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
				</script>

				<%end%>

				<% @todos.each do |t|%>
				<p>

					<strong><%= t.name%></strong>
					<small><%= link_to "Mark as Done", todoo_path(t), :method => :put %></small>

				</p>

				<%end%>
			</div>
			<div class="col-md-6">
				<h2>Finished reading</h2>

				<% if @todone.empty? %>
				<p> You've accomplished nothing. Get reading! </p>

				<a href="https://twitter.com/intent/tweet?button_hashtag=ReadingChallenge2015&text=I'm%20starting%20the%202015%20Reading%20Challenge!" class="twitter-hashtag-button" data-related="superandomness" data-url="http://readingchallenge2015.herokuapp.com">Tweet #ReadingChallenge2015</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

				<%end%>

				<% @todone.each do |t|%>
				<p>
					<%= t.name%>
					<small><%= link_to "Unmark as Done", todoo_path(t), :confirm => "Is it ok to remove this from the list?", :method => :delete %></small>
				</p>

				<%end%>
			</div>
		</div>
	</div>
</div>
<footer>
	<hr>
	<div class="container">
		<div class="row">
			<div class="col-md-6">

			<blockquote>
				<p>Reading is to the mind what exercise is to the body.</p>
				<footer>Joseph Addison</footer>
			</blockquote>

			</div>
			<div class="col-md-6 text-right">
			<address>
				<strong>Built by Cassidy Williams</strong><br>
				<a href="http://cassidoo.co">About</a> -
				<a href="http://github.com/cassidoo">GitHub</a> -
				<a href="http://twitter.com/superandomness">Twitter</a>
				</address>
			</div>
		</div>
	</div>
</footer>

app/views/todoo/new.html.erb
<!-- This file is unused, unless we enable adding new items to the list. -->

<h1>Add new item to your todoo list</h1>

<%= form_for @todo, :url => todoo_index_path(@todo) do |f| %>	<%= f.label :name%>: <%= f.text_field :name%>
<%= f.hidden_field :done, :value => false %>
<%= f.submit "Add to todoo list"%>

<%end%>